# Numpy - Operations

In [1]:
import numpy as np

In [4]:
array1=np.arange(1,5)

In [5]:
array1

array([1, 2, 3, 4])

In [10]:
array2=np.arange(5,9)

In [11]:
array2

array([5, 6, 7, 8])

In [12]:
array1+array2

array([ 6,  8, 10, 12])

In [13]:
array1*array2

array([ 5, 12, 21, 32])

In [14]:
array1-array2

array([-4, -4, -4, -4])

In [15]:
array1/array2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [16]:
array1*array1

array([ 1,  4,  9, 16])

In [18]:
array1+2

array([3, 4, 5, 6])

In [21]:
np.sqrt(array1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
np.sqrt(array2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [23]:
np.power(array1,4)

array([  1,  16,  81, 256], dtype=int32)