# Numpy

In [1]:
#Array

In [2]:
import numpy as np

In [3]:
list=[1,2,3,4,5,6]

In [4]:
array1=np.array(list)

In [5]:
array1

array([1, 2, 3, 4, 5, 6])

In [6]:
matrix=[[1,2,3,4],[5,6,7,8]]

In [7]:
np.array(matrix)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#2 Dimension array

In [9]:
# Generate random

In [10]:
np.random.random()

0.43451563163302687

In [11]:
np.random.random(6)

array([0.89648977, 0.72468214, 0.93056487, 0.91780321, 0.34688373,
       0.45837898])

In [13]:
np.random.randint(0,10,(2,2))

array([[7, 4],
       [0, 6]])

In [15]:
np.arange(0,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
np.arange(1,6,2)

array([1, 3, 5])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.ones(((4,4,2)))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
# Reshape (số phần tử = dòng * cột, cột * dòng mới thực hiện đc)

In [22]:
array2=np.arange(1,10)

In [23]:
array1.shape

(6,)

In [24]:
array2.shape

(9,)

In [25]:
array2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array3=np.arange(1,9)

In [31]:
array3.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
array3.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
a = array3.reshape(4,2)

In [35]:
a.shape

(4, 2)