# Numpy indexing


In [1]:
import numpy as np

In [2]:
array1=np.arange(0,11)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array1[5]

5

In [5]:
array1[2:7]

array([2, 3, 4, 5, 6])

In [6]:
array1[:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
#Reassign

In [8]:
array1[3:8] = 7

In [9]:
array1

array([ 0,  1,  2,  7,  7,  7,  7,  7,  8,  9, 10])

In [10]:
# .copy()

In [11]:
arr_copy = array1.copy()

In [12]:
arr_copy

array([ 0,  1,  2,  7,  7,  7,  7,  7,  8,  9, 10])

In [13]:
arr_copy[4:7]=12

In [14]:
arr_copy

array([ 0,  1,  2,  7, 12, 12, 12,  7,  8,  9, 10])

In [15]:
array1

array([ 0,  1,  2,  7,  7,  7,  7,  7,  8,  9, 10])

In [16]:
x = np.array([[1,2,3,4],[9,8,7,6]])

In [18]:
x

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [20]:
x[1]

array([9, 8, 7, 6])

In [21]:
x[1][2]

7

In [22]:
x[1,2]

7

In [23]:
x[0,3]

4

In [24]:
#Conditional indexing (index dựa trên điều kiện)

In [26]:
z=np.arange(0,20,3)

In [27]:
z

array([ 0,  3,  6,  9, 12, 15, 18])

In [29]:
cond = z<2

In [30]:
z[cond]

array([0])

In [31]:
cond=z>10

In [32]:
z[cond]

array([12, 15, 18])

In [34]:
z[z>9]

array([12, 15, 18])

In [35]:
z[z<15]

array([ 0,  3,  6,  9, 12])